// Code generated by apps/alerting/hack/gen-metadata. DO NOT EDIT.

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// DummyMetadata is the metadata schema type for Dummy, using the shared CommonMetadata type.
type DummyMetadata = resource.CommonMetadata

// NewDummyMetadata creates a new DummyMetadata object.
func NewDummyMetadata() *DummyMetadata {
	md := resource.CommonMetadata{
		Finalizers: []string{},
		Labels:     map[string]string{},
	}
	return &md
}
