package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type kindConfig struct {
	machineName string
	typeName    string
}

type appConfig struct {
	goPkgRelPath string
	tsBasePath   string
	tsEnabled    bool
	versions     map[string][]kindConfig
}

var appConfigs = map[string]appConfig{
	"rules": {
		goPkgRelPath: "pkg/apis/alerting",
		tsBasePath:   "plugin/src/generated",
		tsEnabled:    true,
		versions: map[string][]kindConfig{
			"v0alpha1": {
				{machineName: "alertrule", typeName: "AlertRule"},
				{machineName: "recordingrule", typeName: "RecordingRule"},
				{machineName: "rulesequence", typeName: "RuleSequence"},
			},
		},
	},
	"notifications": {
		goPkgRelPath: "pkg/apis/alertingnotifications",
		tsEnabled:    false,
		versions: map[string][]kindConfig{
			"v0alpha1": {
				{machineName: "receiver", typeName: "Receiver"},
				{machineName: "routingtree", typeName: "RoutingTree"},
				{machineName: "templategroup", typeName: "TemplateGroup"},
				{machineName: "timeinterval", typeName: "TimeInterval"},
				{machineName: "inhibitionrule", typeName: "InhibitionRule"},
			},
			"v1beta1": {
				{machineName: "receiver", typeName: "Receiver"},
				{machineName: "routingtree", typeName: "RoutingTree"},
				{machineName: "templategroup", typeName: "TemplateGroup"},
				{machineName: "timeinterval", typeName: "TimeInterval"},
				{machineName: "inhibitionrule", typeName: "InhibitionRule"},
			},
		},
	},
	"historian": {
		goPkgRelPath: "pkg/apis/alertinghistorian",
		tsBasePath:   "plugin/src/generated",
		tsEnabled:    true,
		versions: map[string][]kindConfig{
			"v0alpha1": {
				{machineName: "dummy", typeName: "Dummy"},
			},
		},
	},
}

func main() {
	appName := flag.String("app", "", "alerting app name (rules, notifications, historian)")
	flag.Parse()

	if *appName == "" {
		fmt.Fprintln(os.Stderr, "--app is required")
		os.Exit(1)
	}

	cfg, ok := appConfigs[*appName]
	if !ok {
		fmt.Fprintf(os.Stderr, "unknown app %q\n", *appName)
		os.Exit(1)
	}

	cwd, err := os.Getwd()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	for version, kinds := range cfg.versions {
		for _, kind := range kinds {
			goOut := filepath.Join(cwd, cfg.goPkgRelPath, version, fmt.Sprintf("%s_metadata_gen.go", kind.machineName))
			if err := os.WriteFile(goOut, []byte(goMetadataTemplate(version, kind.typeName)), 0o644); err != nil {
				fmt.Fprintln(os.Stderr, err)
				os.Exit(1)
			}

			if cfg.tsEnabled {
				tsOut := filepath.Join(cwd, cfg.tsBasePath, kind.machineName, version, "types.metadata.gen.ts")
				importPath, err := relativeImportPath(tsOut, filepath.Join(cwd, "..", "metadata", "common_metadata.ts"))
				if err != nil {
					fmt.Fprintln(os.Stderr, err)
					os.Exit(1)
				}
				if err := os.WriteFile(tsOut, []byte(tsMetadataTemplate(importPath)), 0o644); err != nil {
					fmt.Fprintln(os.Stderr, err)
					os.Exit(1)
				}
			}
		}
	}
}

func goMetadataTemplate(version, typeName string) string {
	metadataType := typeName + "Metadata"
	return fmt.Sprintf(`// Code generated by apps/alerting/hack/gen-metadata. DO NOT EDIT.

package %s

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// %s is the metadata schema type for %s, using the shared CommonMetadata type.
type %s = resource.CommonMetadata

// New%s creates a new %s object.
func New%s() *%s {
	md := resource.CommonMetadata{
		Finalizers: []string{},
		Labels:     map[string]string{},
	}
	return &md
}
`, version, metadataType, typeName, metadataType, metadataType, metadataType, metadataType, metadataType)
}

func tsMetadataTemplate(importPath string) string {
	return fmt.Sprintf(`// Code generated by apps/alerting/hack/gen-metadata. DO NOT EDIT.

export type { CommonMetadata as Metadata } from '%s';
export { defaultCommonMetadata as defaultMetadata } from '%s';
`, importPath, importPath)
}

func relativeImportPath(fromFile, toFile string) (string, error) {
	fromDir := filepath.Dir(fromFile)
	rel, err := filepath.Rel(fromDir, toFile)
	if err != nil {
		return "", err
	}
	rel = strings.TrimSuffix(rel, filepath.Ext(rel))
	return "./" + filepath.ToSlash(rel), nil
}
