import { type CodeHealthMetric, type RecommendedAction, type TimeRange } from './types';

const metricsByRange: Record<TimeRange, CodeHealthMetric[]> = {
  '7d': [
    {
      id: 'lint-errors',
      label: 'Lint errors',
      value: 42,
      status: 'warning',
      trend: 'down',
      trendDelta: -8,
      description: 'ESLint errors across changed files in the last 7 days.',
      icon: 'exclamation-triangle',
      history: [62, 58, 55, 53, 50, 47, 42],
    },
    {
      id: 'type-errors',
      label: 'TypeScript errors',
      value: 6,
      status: 'critical',
      trend: 'up',
      trendDelta: 2,
      description: 'tsc --noEmit failures from the most recent CI runs.',
      icon: 'bug',
      history: [4, 4, 5, 5, 6, 6, 6],
    },
    {
      id: 'flaky-tests',
      label: 'Flaky tests',
      value: 3,
      status: 'warning',
      trend: 'flat',
      trendDelta: 0,
      description: 'Tests that re-ran at least once in the last 7 days.',
      icon: 'sliders-v-alt',
      history: [3, 3, 3, 3, 3, 3, 3],
    },
    {
      id: 'test-coverage',
      label: 'Test coverage',
      value: 78,
      unit: '%',
      status: 'good',
      trend: 'up',
      trendDelta: 1,
      description: 'Statement coverage from the latest unit test run.',
      icon: 'check-circle',
      history: [76, 76, 77, 77, 77, 78, 78],
    },
    {
      id: 'outdated-deps',
      label: 'Outdated dependencies',
      value: 14,
      status: 'info',
      trend: 'down',
      trendDelta: -3,
      description: 'Direct dependencies behind their latest minor or major.',
      icon: 'shield',
      history: [18, 17, 17, 16, 15, 14, 14],
    },
    {
      id: 'ci-status',
      label: 'CI success rate',
      value: 94,
      unit: '%',
      status: 'good',
      trend: 'up',
      trendDelta: 2,
      description: 'Share of CI runs on main that passed in the last 7 days.',
      icon: 'heart-rate',
      history: [89, 90, 91, 92, 93, 94, 94],
    },
  ],
  '30d': [
    {
      id: 'lint-errors',
      label: 'Lint errors',
      value: 51,
      status: 'warning',
      trend: 'down',
      trendDelta: -19,
      description: 'ESLint errors across changed files in the last 30 days.',
      icon: 'exclamation-triangle',
      history: [70, 68, 64, 60, 58, 54, 51],
    },
    {
      id: 'type-errors',
      label: 'TypeScript errors',
      value: 5,
      status: 'warning',
      trend: 'down',
      trendDelta: -3,
      description: 'tsc --noEmit failures, averaged over the last 30 days.',
      icon: 'bug',
      history: [8, 8, 7, 6, 6, 5, 5],
    },
    {
      id: 'flaky-tests',
      label: 'Flaky tests',
      value: 5,
      status: 'warning',
      trend: 'up',
      trendDelta: 1,
      description: 'Tests that re-ran at least once in the last 30 days.',
      icon: 'sliders-v-alt',
      history: [4, 4, 4, 5, 5, 5, 5],
    },
    {
      id: 'test-coverage',
      label: 'Test coverage',
      value: 77,
      unit: '%',
      status: 'good',
      trend: 'up',
      trendDelta: 2,
      description: 'Average statement coverage from unit tests in the last 30 days.',
      icon: 'check-circle',
      history: [75, 75, 76, 76, 76, 77, 77],
    },
    {
      id: 'outdated-deps',
      label: 'Outdated dependencies',
      value: 16,
      status: 'info',
      trend: 'down',
      trendDelta: -5,
      description: 'Average count of outdated direct dependencies in the last 30 days.',
      icon: 'shield',
      history: [21, 20, 19, 18, 17, 17, 16],
    },
    {
      id: 'ci-status',
      label: 'CI success rate',
      value: 92,
      unit: '%',
      status: 'good',
      trend: 'flat',
      trendDelta: 0,
      description: 'Share of CI runs on main that passed in the last 30 days.',
      icon: 'heart-rate',
      history: [91, 91, 92, 92, 92, 92, 92],
    },
  ],
  '90d': [
    {
      id: 'lint-errors',
      label: 'Lint errors',
      value: 73,
      status: 'critical',
      trend: 'down',
      trendDelta: -32,
      description: 'ESLint errors across changed files in the last 90 days.',
      icon: 'exclamation-triangle',
      history: [105, 98, 92, 88, 84, 79, 73],
    },
    {
      id: 'type-errors',
      label: 'TypeScript errors',
      value: 9,
      status: 'critical',
      trend: 'down',
      trendDelta: -4,
      description: 'tsc --noEmit failures, averaged over the last 90 days.',
      icon: 'bug',
      history: [13, 13, 12, 11, 10, 10, 9],
    },
    {
      id: 'flaky-tests',
      label: 'Flaky tests',
      value: 7,
      status: 'critical',
      trend: 'flat',
      trendDelta: 0,
      description: 'Tests that re-ran at least once in the last 90 days.',
      icon: 'sliders-v-alt',
      history: [7, 7, 7, 7, 7, 7, 7],
    },
    {
      id: 'test-coverage',
      label: 'Test coverage',
      value: 75,
      unit: '%',
      status: 'warning',
      trend: 'up',
      trendDelta: 4,
      description: 'Average statement coverage from unit tests in the last 90 days.',
      icon: 'check-circle',
      history: [71, 72, 72, 73, 74, 75, 75],
    },
    {
      id: 'outdated-deps',
      label: 'Outdated dependencies',
      value: 22,
      status: 'warning',
      trend: 'down',
      trendDelta: -7,
      description: 'Average count of outdated direct dependencies in the last 90 days.',
      icon: 'shield',
      history: [29, 28, 26, 25, 24, 23, 22],
    },
    {
      id: 'ci-status',
      label: 'CI success rate',
      value: 88,
      unit: '%',
      status: 'warning',
      trend: 'up',
      trendDelta: 4,
      description: 'Share of CI runs on main that passed in the last 90 days.',
      icon: 'heart-rate',
      history: [84, 85, 86, 87, 87, 88, 88],
    },
  ],
};

const actionsByRange: Record<TimeRange, RecommendedAction[]> = {
  '7d': [
    {
      id: 'fix-type-errors',
      title: 'Resolve 6 TypeScript errors in alerting module',
      description: 'tsc --noEmit reports 6 errors concentrated in public/app/features/alerting/unified.',
      severity: 'high',
      area: 'Alerting',
      metricId: 'type-errors',
    },
    {
      id: 'address-flaky-tests',
      title: 'Quarantine 3 flaky frontend tests',
      description: 'Three Jest specs retried at least once in CI this week. Stabilize or quarantine them.',
      severity: 'medium',
      area: 'Frontend tests',
      metricId: 'flaky-tests',
    },
    {
      id: 'reduce-lint-errors',
      title: 'Drive lint errors below 30 in dashboards',
      description:
        'Most remaining ESLint errors are in public/app/features/dashboard. A targeted sweep should clear ~15.',
      severity: 'medium',
      area: 'Dashboards',
      metricId: 'lint-errors',
    },
    {
      id: 'bump-deps',
      title: 'Bump 14 outdated direct dependencies',
      description: 'Run yarn upgrade-interactive and prioritize security advisories on react-router and zod.',
      severity: 'low',
      area: 'Dependencies',
      metricId: 'outdated-deps',
    },
  ],
  '30d': [
    {
      id: 'fix-type-errors-30',
      title: 'Eliminate the long tail of TypeScript errors',
      description: '5 recurring errors have persisted for the full 30-day window. Time to fix at the source.',
      severity: 'high',
      area: 'Alerting',
      metricId: 'type-errors',
    },
    {
      id: 'flaky-tests-30',
      title: 'Investigate growth in flaky tests',
      description: 'Flaky test count grew from 4 to 5 over the last month.',
      severity: 'medium',
      area: 'Frontend tests',
      metricId: 'flaky-tests',
    },
    {
      id: 'lint-cleanup-30',
      title: 'Continue ESLint cleanup',
      description: 'Errors trending down (-19 over 30 days). Keep momentum with one focused sweep per sprint.',
      severity: 'low',
      area: 'Dashboards',
      metricId: 'lint-errors',
    },
  ],
  '90d': [
    {
      id: 'flaky-tests-90',
      title: 'Stabilize chronic flaky tests',
      description: '7 tests have been flaky for the entire 90-day window. They are blocking confidence in CI.',
      severity: 'high',
      area: 'Frontend tests',
      metricId: 'flaky-tests',
    },
    {
      id: 'coverage-90',
      title: 'Push test coverage above 80%',
      description: 'Coverage has grown from 71% to 75%. Targeted tests in the most-changed packages can clear 80%.',
      severity: 'medium',
      area: 'Coverage',
      metricId: 'test-coverage',
    },
    {
      id: 'outdated-deps-90',
      title: 'Burn down the dependency backlog',
      description: '22 direct dependencies are still behind. Plan a focused upgrade sprint.',
      severity: 'medium',
      area: 'Dependencies',
      metricId: 'outdated-deps',
    },
    {
      id: 'ci-success-90',
      title: 'Lift CI success rate above 95%',
      description: 'Main-branch CI passed 88% of the time over 90 days. Investigate the most common failing jobs.',
      severity: 'low',
      area: 'CI',
      metricId: 'ci-status',
    },
  ],
};

export const TIME_RANGE_OPTIONS: Array<{ label: string; value: TimeRange }> = [
  { label: 'Last 7 days', value: '7d' },
  { label: 'Last 30 days', value: '30d' },
  { label: 'Last 90 days', value: '90d' },
];

export function getMetrics(range: TimeRange): CodeHealthMetric[] {
  return metricsByRange[range];
}

export function getRecommendedActions(range: TimeRange): RecommendedAction[] {
  return actionsByRange[range];
}
