// Code generated by apps/alerting/hack/gen-metadata. DO NOT EDIT.

package v1beta1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// InhibitionRuleMetadata is the metadata schema type for InhibitionRule, using the shared CommonMetadata type.
type InhibitionRuleMetadata = resource.CommonMetadata

// NewInhibitionRuleMetadata creates a new InhibitionRuleMetadata object.
func NewInhibitionRuleMetadata() *InhibitionRuleMetadata {
	md := resource.CommonMetadata{
		Finalizers: []string{},
		Labels:     map[string]string{},
	}
	return &md
}
