// Code generated by apps/alerting/hack/gen-metadata. DO NOT EDIT.

package v1beta1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// ReceiverMetadata is the metadata schema type for Receiver, using the shared CommonMetadata type.
type ReceiverMetadata = resource.CommonMetadata

// NewReceiverMetadata creates a new ReceiverMetadata object.
func NewReceiverMetadata() *ReceiverMetadata {
	md := resource.CommonMetadata{
		Finalizers: []string{},
		Labels:     map[string]string{},
	}
	return &md
}
