// Code generated by apps/alerting/hack/gen-metadata. DO NOT EDIT.

package v1beta1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// TemplateGroupMetadata is the metadata schema type for TemplateGroup, using the shared CommonMetadata type.
type TemplateGroupMetadata = resource.CommonMetadata

// NewTemplateGroupMetadata creates a new TemplateGroupMetadata object.
func NewTemplateGroupMetadata() *TemplateGroupMetadata {
	md := resource.CommonMetadata{
		Finalizers: []string{},
		Labels:     map[string]string{},
	}
	return &md
}
