// Code generated by apps/alerting/hack/gen-metadata. DO NOT EDIT.

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// RoutingTreeMetadata is the metadata schema type for RoutingTree, using the shared CommonMetadata type.
type RoutingTreeMetadata = resource.CommonMetadata

// NewRoutingTreeMetadata creates a new RoutingTreeMetadata object.
func NewRoutingTreeMetadata() *RoutingTreeMetadata {
	md := resource.CommonMetadata{
		Finalizers: []string{},
		Labels:     map[string]string{},
	}
	return &md
}
