// Code generated by apps/alerting/hack/gen-metadata. DO NOT EDIT.

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// TimeIntervalMetadata is the metadata schema type for TimeInterval, using the shared CommonMetadata type.
type TimeIntervalMetadata = resource.CommonMetadata

// NewTimeIntervalMetadata creates a new TimeIntervalMetadata object.
func NewTimeIntervalMetadata() *TimeIntervalMetadata {
	md := resource.CommonMetadata{
		Finalizers: []string{},
		Labels:     map[string]string{},
	}
	return &md
}
