//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v0alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *Organization) DeepCopyInto(out *Organization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *Organization) DeepCopy() *Organization {
	if in == nil {
		return nil
	}
	out := new(Organization)
	in.DeepCopyInto(out)
	return out
}

func (in *Organization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OrganizationList) DeepCopyInto(out *OrganizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Organization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OrganizationList) DeepCopy() *OrganizationList {
	if in == nil {
		return nil
	}
	out := new(OrganizationList)
	in.DeepCopyInto(out)
	return out
}

func (in *OrganizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OrganizationSpec) DeepCopyInto(out *OrganizationSpec) {
	*out = *in
}

func (in *OrganizationSpec) DeepCopy() *OrganizationSpec {
	if in == nil {
		return nil
	}
	out := new(OrganizationSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OrgMembership) DeepCopyInto(out *OrgMembership) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *OrgMembership) DeepCopy() *OrgMembership {
	if in == nil {
		return nil
	}
	out := new(OrgMembership)
	in.DeepCopyInto(out)
	return out
}

func (in *OrgMembership) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OrgMembershipList) DeepCopyInto(out *OrgMembershipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OrgMembership, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OrgMembershipList) DeepCopy() *OrgMembershipList {
	if in == nil {
		return nil
	}
	out := new(OrgMembershipList)
	in.DeepCopyInto(out)
	return out
}

func (in *OrgMembershipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OrgMembershipSpec) DeepCopyInto(out *OrgMembershipSpec) {
	*out = *in
}

func (in *OrgMembershipSpec) DeepCopy() *OrgMembershipSpec {
	if in == nil {
		return nil
	}
	out := new(OrgMembershipSpec)
	in.DeepCopyInto(out)
	return out
}
