// Code generated by apps/alerting/hack/gen-metadata. DO NOT EDIT.

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// AlertRuleMetadata is the metadata schema type for AlertRule, using the shared CommonMetadata type.
type AlertRuleMetadata = resource.CommonMetadata

// NewAlertRuleMetadata creates a new AlertRuleMetadata object.
func NewAlertRuleMetadata() *AlertRuleMetadata {
	md := resource.CommonMetadata{
		Finalizers: []string{},
		Labels:     map[string]string{},
	}
	return &md
}
