// Code generated by apps/alerting/hack/gen-metadata. DO NOT EDIT.

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// RecordingRuleMetadata is the metadata schema type for RecordingRule, using the shared CommonMetadata type.
type RecordingRuleMetadata = resource.CommonMetadata

// NewRecordingRuleMetadata creates a new RecordingRuleMetadata object.
func NewRecordingRuleMetadata() *RecordingRuleMetadata {
	md := resource.CommonMetadata{
		Finalizers: []string{},
		Labels:     map[string]string{},
	}
	return &md
}
