// Code generated by apps/alerting/hack/gen-metadata. DO NOT EDIT.

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// RuleSequenceMetadata is the metadata schema type for RuleSequence, using the shared CommonMetadata type.
type RuleSequenceMetadata = resource.CommonMetadata

// NewRuleSequenceMetadata creates a new RuleSequenceMetadata object.
func NewRuleSequenceMetadata() *RuleSequenceMetadata {
	md := resource.CommonMetadata{
		Finalizers: []string{},
		Labels:     map[string]string{},
	}
	return &md
}
